spring.application.name=backend

spring.mongodb.uri=mongodb://localhost:27017/chatapp

# add commands to show logs in the console along with db queries


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.format_sql=true

